sudo: required
services: 
  - docker
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
install: true

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gccloud auth activate-service-account --key-file service-account.json

