os: linux
language: node_js
node_js:
    - 12.4.0
services:
    - docker
    
before_install:
    - docker build -t anilverma/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true anilverma/docker-react npm run test
    
    

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY"
    
  secret_access_key: "$AWS_SECRET_KEY"
    
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-002829650677"  
  bucket_path: "docker-react" 
  on:
    branch: master  
    
    
    
    
    